/*----------------------------------------------------------
MASV:20120262
HO TEN: KHÚC KHÁNH ĐĂNG
LAB: 03
NGAY: 13/04/2023
----------------------------------------------------------*/
--CAU LENH TAO DB
use master
DROP DATABASE IF EXISTS QLSV
go
CREATE DATABASE QLSV
go
/*----------------------------------------------------------
MASV:20120262
HO TEN: KHÚC KHÁNH ĐĂNG
LAB: 03
NGAY: 13/04/2023
----------------------------------------------------------*/
--- CAC CAU LENH TAO TABLE

USE QLSV

DROP TABLE IF EXISTS NHANVIEN
GO
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20) NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(max),
	TENDN NVARCHAR(100)NOT NULL,
	MATKHAU VARBINARY(max) NOT NULL,
	CONSTRAINT PK_NV PRIMARY KEY (MANV)
)
DROP TABLE IF EXISTS SINHVIEN
GO
CREATE TABLE SINHVIEN
(
	MASV NVARCHAR(20) NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH datetime,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100)NOT NULL,
	MATKHAU VARBINARY(max) NOT NULL
	CONSTRAINT PK_SV PRIMARY KEY(MASV)
)
DROP TABLE IF EXISTS LOP
GO
CREATE TABLE LOP
(
	MALOP VARCHAR(20),
	TEN NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)
	CONSTRAINT PK_L PRIMARY KEY(MALOP)
)

-- QUAN HE
--ALTER TABLE LOP
--ADD CONSTRAINT FK_L_NV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)

--ALTER TABLE SINHVIEN
--ADD CONSTRAINT FK_SV_L FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)

/*----------------------------------------------------------
MASV:20120262
HO TEN: KHÚC KHÁNH ĐĂNG
LAB: 03
NGAY: 13/04/2023
----------------------------------------------------------*/
--- CAU LENH TAO STORED PROCEDURE
--- TAO STORED SP_INS_SINHVIEN

DROP PROCEDURE IF EXISTS SP_INS_SINHVIEN;
GO

CREATE PROC SP_INS_SINHVIEN(
	@MASV NVARCHAR(20),
	@HOTEN NVARCHAR(100),
	@NGAYSINH DATETIME,
	@DIACHI NVARCHAR(200),
	@MALOP VARCHAR(20),
	@TENDN NVARCHAR(100),
	@MATKHAU VARCHAR(32)
)
AS
	BEGIN
		DECLARE @ENKEY VARBINARY(max);
		SET @ENKEY = CONVERT(VARBINARY,HASHBYTES('MD5', @MATKHAU));
		INSERT INTO SINHVIEN
		VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @ENKEY)
	END;
GO
EXEC SP_INS_SINHVIEN 'SV01', 'NGUYEN VAN A', '1/1/1990', '280 AN DUONG VUONG', 'CNTT-K35', 'NVA', '123456'
select * from SINHVIEN
GO

--tao MASTERKEY
IF NOT EXISTS
(
	SELECT*
	from sys.symmetric_keys
	WHERE symmetric_key_id = 101
)

CREATE MASTER KEY ENCRYPTION by
	PASSWORD = '20120262'
GO

--tao CERTIFICATE
IF NOT EXISTS
(
	SELECT*
	from sys.certificates
	WHERE name = 'MyCert'
)

CREATE CERTIFICATE myCert
	WITH SUBJECT = 'MyCert'
GO
--drop master key
--drop certificate myCert
--tao SYMMETRIC KEY
IF NOT EXISTS
(
	SELECT*
	from sys.symmetric_keys
	WHERE NAME = 'PriKey'
)
CREATE SYMMETRIC KEY PriKey
WITH ALGORITHM = AES_256
ENCRYPTION BY CERTIFICATE MyCert;
GO

drop proc if EXISTS SP_INS_NHANVIEN

go

--SP_INS_NHANVIEN
CREATE PROCEDURE SP_INS_NHANVIEN
(
	@MANV VARCHAR(20),
	@HOTEN NVARCHAR(100),
	@EMAIL VARCHAR(20),
	@LUONG INT,
	@TENDN NVARCHAR(100),
	@MATKHAU VARCHAR(32)
)
AS
	BEGIN
		OPEN SYMMETRIC KEY PriKey
		DECRYPTION BY CERTIFICATE MyCert; 
		DECLARE @ENPASS varbinary(max);
		DECLARE @ENSAL varbinary(max);
		SET @ENPASS=CONVERT(varbinary, HashBytes('SHA1',@MATKHAU));
		SET @ENSAL = ENCRYPTBYKEY(KEY_GUID('PriKey'), CONVERT(varbinary(MAX), @LUONG))
		insert into NHANVIEN(MANV,HOTEN,EMAIL,LUONG,TENDN,MATKHAU)
		values (@MANV, @HOTEN, @EMAIL, @ENSAL, @TENDN,@ENPASS);
	END

--drop procedure SP_INS_NHANVIEN
GO

GO

EXEC SP_INS_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@', 3000000, 'NVA', 'abcd12'
select * from nhanvien

GO
DROP PROCEDURE IF EXISTS SP_SEL_NHANVIEN;
GO
CREATE PROC SP_SEL_NHANVIEN
AS
	BEGIN
		OPEN SYMMETRIC KEY PriKey
		DECRYPTION BY CERTIFICATE MyCert;
		SELECT MANV,HOTEN,EMAIL,CONVERT(int, DECRYPTBYKEY(LUONG)) as LUONGCB
		FROM NHANVIEN
	END

--drop procedure SP_SEL_NHANVIEN

GO


EXEC SP_SEL_NHANVIEN
